# where the repository lives
repo_dir: /nfshome/bwedig/mejiro

# where output data should be written
data_dir: /data/bwedig/roman-pandeia

# specify additional directories here to ensure consistency
array_dir: ${machine.data_dir}/output/arrays
figure_dir: ${machine.repo_dir}/figures
pickle_dir: ${machine.data_dir}/output/pickles
sample_dir: ${machine.pickle_dir}/03_models_and_updated_lenses
pandeia_dir: ${machine.array_dir}/04_pandeia_output_color