# where the repository lives
repo_dir: /Users/brycewedig/Documents/GitHub/mejiro

# where output data should be written
data_dir: /Users/brycewedig/Documents/GitHub data/mejiro

# specify additional directories here to ensure consistency
array_dir: ${machine.data_dir}/output/arrays
figure_dir: ${machine.repo_dir}/figures
pickle_dir: ${machine.data_dir}/output/pickles

# pipeline directories
sample_dir: ${machine.pickle_dir}/03_models_and_updated_lenses
pandeia_dir: ${machine.array_dir}/04_pandeia_output
color_dir: ${machine.array_dir}/05_color