# where the repository lives
repo_dir: /home/btwedig/mejiro

# where output data should be written
data_dir: /data/scratch/btwedig/mejiro

# specify additional directories here to ensure consistency
array_dir: ${machine.data_dir}/output/arrays
figure_dir: ${machine.repo_dir}/figures
pickle_dir: ${machine.data_dir}/output/pickles