"""
Simulates a strong lensing survey using pre-computed galaxy tables from _01a.

This script loads galaxy population tables generated by _01a_generate_galaxy_tables.py,
reconstructs the lens population objects, and runs the survey simulation. This avoids
the expensive SkyPy/SLHammocks initialization that dominates runtime in the original _01.

Each run is assigned a galaxy table via round-robin (run_index % num_galaxy_tables).
Per-run random seeding ensures reproducible, unique draws across runs.

Usage:
    python3 _01b_run_survey_simulation.py --config <config.yaml> [--data_dir <output_dir>]

Arguments:
    --config: Path to the YAML configuration file.
    --data_dir: Optional override for the data directory specified in the config file.
"""
import os
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["JAX_PLATFORM_NAME"] = "cpu"  # prevent JAX from claiming GPU before config is loaded
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"  # prevent greedy GPU memory preallocation

import argparse
import time
import warnings
from concurrent.futures import ProcessPoolExecutor, as_completed
from glob import glob

import numpy as np
from astropy.cosmology import default_cosmology
from astropy.units import Quantity
from slsim.Lenses.lens_pop import LensPop
import slsim.Sources as sources
import slsim.Deflectors as deflectors
from tqdm import tqdm

import mejiro
from mejiro.analysis import snr_calculation
from mejiro.exposure import Exposure
from mejiro.galaxy_galaxy import GalaxyGalaxy
from mejiro.synthetic_image import SyntheticImage
from mejiro.utils import roman_util, slsim_util, util
from mejiro.utils.pipeline_helper import PipelineHelper

import logging
logger = logging.getLogger(__name__)


PREV_SCRIPT_NAME = '01a'
SCRIPT_NAME = '01b'
SUPPORTED_INSTRUMENTS = ['roman', 'jwst', 'hwo']


def main(args):
    start = time.time()

    # initialize PipelineHelper
    pipeline = PipelineHelper(args, PREV_SCRIPT_NAME, SCRIPT_NAME, SUPPORTED_INSTRUMENTS, delete_existing_output=False)

    # set configuration parameters
    pipeline.config['survey']['cosmo'] = default_cosmology.get()
    os.environ['JAX_PLATFORM_NAME'] = pipeline.config['jaxtronomy'].get('jax_platform', 'cpu')

    # discover pre-computed galaxy tables from _01a
    galaxy_table_paths = sorted(glob(os.path.join(pipeline.input_dir, 'galaxy_table_*.pkl')))
    num_galaxy_tables = len(galaxy_table_paths)
    if num_galaxy_tables == 0:
        raise FileNotFoundError(f'No galaxy tables found in {pipeline.input_dir}. Run _01a first.')
    logger.info(f'Found {num_galaxy_tables} pre-computed galaxy table(s) in {pipeline.input_dir}')

    # tuple the parameters
    tuple_list = []
    for run in range(pipeline.runs):
        if pipeline.instrument.num_detectors > 1:
            detector = pipeline.detectors[run % len(pipeline.detectors)]
        else:
            detector = None
        table_path = galaxy_table_paths[run % num_galaxy_tables]
        tuple_list.append((str(run).zfill(4), detector, table_path, pipeline.config,
                           pipeline.output_dir, pipeline.psf_cache_dir, pipeline.instrument))

    # check for already-completed runs from a previous (incomplete) execution
    def _run_id(run_str, detector):
        if pipeline.instrument.name == 'Roman':
            return f'{run_str}_{roman_util.get_sca_string(detector).lower()}'
        return run_str

    num_detectable = 0
    skipped = 0
    filtered_tuple_list = []
    for params in tuple_list:
        run_str, detector = params[0], params[1]
        rid = _run_id(run_str, detector)
        sentinel = os.path.join(pipeline.output_dir, f'run_complete_{rid}.txt')
        if os.path.exists(sentinel):
            with open(sentinel) as f:
                num_detectable += int(f.read().strip())
            skipped += 1
        else:
            filtered_tuple_list.append(params)

    if skipped:
        logger.info(f'Skipping {skipped} already-completed run(s); resuming {len(filtered_tuple_list)} remaining run(s).')

    if not filtered_tuple_list:
        logger.info('All runs already completed. Nothing to do.')
        logger.info(f'{num_detectable} detectable lenses found')
        logger.info(f'{num_detectable / pipeline.config["survey"]["area"] / pipeline.runs:.2f} per square degree')
        stop = time.time()
        execution_time = util.print_execution_time(start, stop, return_string=True)
        util.write_execution_time(execution_time, '01b', os.path.join(pipeline.pipeline_dir, 'execution_times.json'))
        return

    # process the remaining tasks with ProcessPoolExecutor
    num_workers = pipeline.calculate_process_count(len(filtered_tuple_list))
    try:
        with ProcessPoolExecutor(max_workers=num_workers) as executor:
            futures = [executor.submit(run_slsim, task) for task in filtered_tuple_list]

            for future in tqdm(as_completed(futures), total=len(filtered_tuple_list)):
                num_detectable += future.result()
    except KeyboardInterrupt:
        logger.info('Interrupted, shutting down workers...')
        executor.shutdown(wait=False, cancel_futures=True)
        raise

    logger.info(f'{num_detectable} detectable lenses found')
    logger.info(f'{num_detectable / pipeline.config["survey"]["area"] / pipeline.runs:.2f} per square degree')

    stop = time.time()
    execution_time = util.print_execution_time(start, stop, return_string=True)
    util.write_execution_time(execution_time, '01b', os.path.join(pipeline.pipeline_dir, 'execution_times.json'))


def run_slsim(tuple):
    # unpack tuple
    run, detector, table_path, config, output_dir, psf_cache_dir, instrument = tuple

    # reproducible per-run seeding
    global_seed = config.get('seed', 42)
    np.random.seed(hash((global_seed, int(run))) % (2**32))

    # suppress warnings
    if config['suppress_warnings']:
        warnings.filterwarnings("ignore")

    # retrieve configuration parameters
    limit = config['limit']
    snr_config = config['snr']
    show_progress_bar = config['show_progress_bar']
    use_jax = config['jaxtronomy']['use_jax']
    engine_params = config['imaging']['engine_params']
    survey_config = config['survey']
    area = survey_config['area']
    bands = survey_config['bands']
    cosmo = survey_config['cosmo']
    use_real_sources = survey_config['use_real_sources']
    use_slhammocks_pipeline = survey_config['use_slhammocks_pipeline']
    speed_factor = survey_config.get('speed_factor', 1)
    num_pix = config['psf']['num_pixes'][0]
    snr_band = snr_config['snr_band']
    snr_exposure_time = snr_config['snr_exposure_time']
    snr_fov_arcsec = snr_config['snr_fov_arcsec']
    snr_supersampling_factor = snr_config['snr_supersampling_factor']
    snr_supersampling_compute_mode = snr_config['snr_supersampling_compute_mode']
    snr_per_pixel_threshold = snr_config['snr_per_pixel_threshold']
    snr_kwargs_numerics = {
        'supersampling_factor': snr_supersampling_factor,
        'compute_mode': snr_supersampling_compute_mode,
    }
    snr_detector = detector
    snr_detector_position = (2554, 2554)

    # set run identifier
    if instrument.name == 'Roman':
        run_id = f'{run}_{roman_util.get_sca_string(detector).lower()}'
    elif instrument.name == 'HWO' or instrument.name == 'JWST':
        run_id = str(run).zfill(4)
    else:
        raise ValueError(f"Run identifier not implemented for {instrument.name}.")

    # load filters
    if config['pipeline_label'] == 'all':
        from mejiro.instruments.hst import HST
        from mejiro.instruments.jwst import JWST
        from mejiro.instruments.roman import Roman
        from mejiro.instruments.hwo import HWO
        speclite_filters = Roman.load_speclite_filters(detector='SCA01')
        speclite_filters = HST.load_speclite_filters()
        speclite_filters = JWST.load_speclite_filters()
        speclite_filters = HWO.load_speclite_filters()
    elif instrument.name == 'Roman':
        detector_string = roman_util.get_sca_string(detector).lower()
        filter_args = {'detector': detector_string}
        speclite_filters = instrument.load_speclite_filters(**filter_args)
    elif instrument.name == 'HWO' or instrument.name == 'JWST':
        filter_args = {}
        speclite_filters = instrument.load_speclite_filters(**filter_args)
    else:
        raise ValueError(f"Speclite filter loading not implemented for {instrument.name}.")

    logger.info(f'Loaded {instrument.name} filter response curve(s): {speclite_filters.names}')

    # load pre-computed galaxy table
    galaxy_data = util.unpickle(table_path)
    logger.info(f'Loaded galaxy table from {table_path}')

    # set survey parameters
    sky_area = Quantity(value=area, unit='deg2')

    # define cuts on the intrinsic deflector and source populations
    kwargs_deflector_cut = {
        'band': survey_config['deflector_cut_band'],
        'band_max': survey_config['deflector_cut_band_max'],
        'z_min': survey_config['deflector_z_min'],
        'z_max': survey_config['deflector_z_max']
    }
    kwargs_source_cut = {
        'band': survey_config['source_cut_band'],
        'band_max': survey_config['source_cut_band_max'],
        'z_min': survey_config['source_z_min'],
        'z_max': survey_config['source_z_max']
    }

    # reconstruct the lens population from pre-computed tables
    logger.info('Reconstructing galaxy population from pre-computed tables...')
    if use_slhammocks_pipeline:
        lens_galaxies = deflectors.CompoundLensHalosGalaxies(
            halo_galaxy_list=galaxy_data['halo_galaxies'],
            kwargs_cut=kwargs_deflector_cut,
            kwargs_mass2light={},
            cosmo=cosmo,
            sky_area=sky_area,
        )
    else:
        lens_galaxies = deflectors.AllLensGalaxies(
            red_galaxy_list=galaxy_data['red_galaxies'],
            blue_galaxy_list=galaxy_data['blue_galaxies'],
            kwargs_cut=kwargs_deflector_cut,
            kwargs_mass2light={},
            cosmo=cosmo,
            sky_area=sky_area,
        )
    real_galaxy_kwargs = {
        "extended_source_type": "catalog_source",
        "extended_source_kwargs": survey_config["catalog_source_kwargs"]
    } if use_real_sources else {}
    source_galaxies = sources.Galaxies(
        galaxy_list=galaxy_data['blue_galaxies'],
        kwargs_cut=kwargs_source_cut,
        cosmo=cosmo,
        sky_area=sky_area,
        catalog_type="skypy",
        source_size=None,
        **real_galaxy_kwargs
    )
    lens_pop = LensPop(
        deflector_population=lens_galaxies,
        source_population=source_galaxies,
        cosmo=cosmo,
        sky_area=sky_area,
    )
    logger.info('Reconstructed galaxy population')

    # get PSF parameters for SNR calculation
    instrument_psf_kwargs = {
        'band': snr_band,
        'detector': snr_detector,
        'detector_position': snr_detector_position,
        'oversample': snr_supersampling_factor,
        'num_pix': num_pix,
        'check_cache': True,
        'psf_cache_dir': psf_cache_dir,
    }
    kwargs_psf = instrument.get_psf_kwargs(**instrument_psf_kwargs)

    # draw the total lens population
    if survey_config['total_population']:
        logger.info('Identifying lenses...')
        kwargs_lens_total_cut = {
            'min_image_separation': 0,
            'max_image_separation': 10,
            'mag_arc_limit': None
        }
        total_lens_population = lens_pop.draw_population(kwargs_lens_cuts=kwargs_lens_total_cut,
                                                          speed_factor=speed_factor)
        logger.info(f'Number of total lenses: {len(total_lens_population)}')

        # compute SNRs and save
        logger.info(f'Computing SNRs for {len(total_lens_population)} lenses')
        snr_list = []
        num_exceptions = 0
        for candidate in tqdm(total_lens_population, disable=not show_progress_bar):
            strong_lens = GalaxyGalaxy.from_slsim(candidate, bands=bands, use_jax=use_jax)

            # TODO temporary fix to make sure that there are two images formed
            image_positions = strong_lens.get_image_positions()
            if len(image_positions[0]) < 2:
                continue

            # TODO do something with the substract lens flag
            # TODO do something with the add subhalos flag

            # calculate SNR
            synthetic_image = SyntheticImage(strong_lens=strong_lens,
                                            instrument=instrument,
                                            band=snr_band,
                                            fov_arcsec=snr_fov_arcsec,
                                            instrument_params={'detector': snr_detector, 'detector_position': snr_detector_position},
                                            kwargs_numerics=snr_kwargs_numerics,
                                            kwargs_psf=kwargs_psf,
                                            pieces=True)
            exposure = Exposure(synthetic_image=synthetic_image,
                                exposure_time=snr_exposure_time,
                                engine='galsim',
                                engine_params=engine_params)
            snr, _ = snr_calculation.get_snr(exposure=exposure,
                                            snr_per_pixel_threshold=snr_per_pixel_threshold)
            snr_list.append(snr)

            if snr is None:
                num_exceptions += 1

        if len(total_lens_population) > 0:
            logger.info(f'Percentage of exceptions: {num_exceptions / len(total_lens_population) * 100:.2f}%')
        else:
            warnings.warn('No systems in total population. Consider revising the galaxy population.')
            return 0

        # save other params to CSV
        if survey_config["write_to_csv"]:
            total_pop_csv = os.path.join(output_dir, f'total_pop_{run_id}.csv')
            logger.info(f'Writing total population to {total_pop_csv}')
            slsim_util.write_lens_population_to_csv(total_pop_csv, total_lens_population, snr_list, bands=bands, show_progress_bar=False)

    # draw initial detectable lens population
    logger.info('Identifying detectable lenses...')
    kwargs_lens_detectable_cut = {
        'min_image_separation': survey_config['min_image_separation'],
        'max_image_separation': survey_config['max_image_separation'],
        'mag_arc_limit': {survey_config['mag_arc_limit_band']: survey_config['mag_arc_limit']}
    }
    lens_population = lens_pop.draw_population(kwargs_lens_cuts=kwargs_lens_detectable_cut,
                                                speed_factor=speed_factor)
    logger.info(f'Number of detectable lenses from first set of criteria: {len(lens_population)}')

    # apply additional detectability criteria
    detectable_gglenses, detectable_snr_list, masked_snr_array_list = [], [], []
    for candidate in tqdm(lens_population, disable=not show_progress_bar):
        # convert from SLSim gglens to mejiro GalaxyGalaxy
        try:
            strong_lens = GalaxyGalaxy.from_slsim(candidate, bands=bands, use_jax=use_jax)
        except:
            logger.warning(f'Error processing candidate {candidate["name"]}')
            continue

        # TODO do something with the substract lens flag
        # TODO do something with the add subhalos flag

        # pre-filter: magnification check (before expensive SNR calculation)
        magnification = strong_lens.physical_params['magnification']
        if magnification < survey_config['magnification']:
            continue

        # pre-filter: image position check
        image_positions = strong_lens.get_image_positions()
        if len(image_positions[0]) < 2:
            continue

        # criterion 1: SNR
        synthetic_image = SyntheticImage(strong_lens=strong_lens,
                                        instrument=instrument,
                                        band=snr_band,
                                        fov_arcsec=snr_fov_arcsec,
                                        instrument_params={'detector': snr_detector, 'detector_position': snr_detector_position},
                                        kwargs_numerics=snr_kwargs_numerics,
                                        kwargs_psf=kwargs_psf,
                                        pieces=True)
        exposure = Exposure(synthetic_image=synthetic_image,
                            exposure_time=snr_exposure_time,
                            engine='galsim',
                            engine_params=engine_params)
        snr, _ = snr_calculation.get_snr(exposure=exposure,
                                                        snr_per_pixel_threshold=snr_per_pixel_threshold)
        if snr is None or snr < snr_config['snr_threshold']:
            continue

        # if both criteria satisfied, consider detectable
        detectable_gglenses.append(candidate)
        detectable_snr_list.append(snr)
        # masked_snr_array_list.append(masked_snr_array)

        # if I've imposed a limit above this loop, exit the loop
        if limit is not None and len(detectable_gglenses) == limit:
            break

    logger.info(f'Run {run}: {len(detectable_gglenses)} detectable lens(es)')

    assert len(detectable_gglenses) == len(
        detectable_snr_list), f'Lengths of detectable_gglenses ({len(detectable_gglenses)}) and detectable_snr_list ({len(detectable_snr_list)}) do not match.'

    if len(detectable_gglenses) > 0:
        # pickle the list of slsim gglenses
        detectable_gglenses_pickle_path = os.path.join(output_dir, f'detectable_gglenses_{run_id}.pkl')
        logger.info(f'Pickling detectable gglenses to {detectable_gglenses_pickle_path}')
        util.pickle(detectable_gglenses_pickle_path, detectable_gglenses)

        # write the parameters of detectable lenses to CSV
        if survey_config["write_to_csv"]:
            detectable_pop_csv = os.path.join(output_dir, f'detectable_pop_{run_id}.csv')
            slsim_util.write_lens_population_to_csv(detectable_pop_csv, detectable_gglenses, detectable_snr_list, bands=bands, show_progress_bar=False)
    else:
        logger.info(f'No detectable lenses found for run {run}')

    # write sentinel file so a resumed execution can skip this run
    sentinel_path = os.path.join(output_dir, f'run_complete_{run_id}.txt')
    with open(sentinel_path, 'w') as f:
        f.write(str(len(detectable_gglenses)))

    return len(detectable_gglenses)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Simulate survey using pre-computed galaxy tables")
    parser.add_argument('--config', type=str, required=True, help='Name of the yaml configuration file.')
    parser.add_argument('--data_dir', type=str, required=False, help='Parent directory of pipeline output. Overrides data_dir in config file if provided.')
    args = parser.parse_args()
    main(args)
