name: mejiro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - astropy
  - galsim
  - jupyter=1.1.1
  - numpy<2
  - pip
  - pytest
  - tqdm
  - pip:
    - hydra-core  # temp
    - lenstronomy
    - webbpsf
    - pandeia-engine==2024.12
    - pysiaf
    - syotools  # for HWO imaging
    - pyhalo
    - colossus  # needed for pyhalo
    - git+https://github.com/bryce-wedig/slsim.git@mejiro-v0.0.3
    # - sncosmo
    # - mcfit
