name: mejiro
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - astroquery
  - jupyter
  - healpy
  - lenstronomy
  - pip
  - tqdm
  - pip:
      - pandeia-engine==3.0
      - pyhalo
      - hydra-core
      - colossus
      - mcfit
      - jwst_backgrounds
      - regions
