name: mejiro-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - astropy=6.1.7
  - galsim=2.5.1
  - jupyter=1.1.1
  - numpy<2
  - pandas=2.2.3
  - pip
  # - pytest  # dev
  - scipy=1.11.4
  - tqdm
  - pip:
    - lenstronomy==1.13.2
    # - jaxtronomy==0.1.0
    - stpsf==2.1.0
    # - pandeia-engine
    - pysiaf==0.24.1
    # - syotools==1.1.13  # for HWO imaging
    - speclite==0.20
    - pyhalo==1.4.3
    - colossus==1.3.3  # needed for pyhalo
    - git+https://github.com/bryce-wedig/slsim.git@mejiro-v2.0.0
    - sncosmo==2.10.4
    - skypy==0.5.3
    - mcfit==0.0.22
    # - git+https://github.com/bryce-wedig/hwo-tools.git@mejiro-v2.0.0
    # - sphinx  # dev
    # - sphinx-rtd-theme  # dev
    - corner==2.2.2
    # - romanisim==0.7.0
    - -e .
