name: mejiro-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - astropy>6.0
  - galsim=2.6.3
  - jupyter
  - pip
  - tqdm
  - pip:
      # - speclite
      - pyhalo==1.3.5
      # - colossus
      # - mcfit
      - stpsf==2.0.0
      - numba==0.58.1
      - lenstronomy==1.12.5
      # - pysiaf
      - pandeia-engine
      # - sncosmo
      - git+https://github.com/bryce-wedig/slsim.git