name: mejiro
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.6
  - astropy
  - astroquery
  - galsim
  - jupyter
  - pip
  - scikit-image
  - skypy
  - tqdm
  - pip:
      - speclite
      - pyhalo
      - hydra-core
      - colossus
      - mcfit
      - webbpsf
      - lenstronomy
      - slsim
      - pysiaf
      - pandeia-engine
