name: mejiro_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - astropy>6.0
  - galsim=2.6.1
  - jupyter
  - pip
  - tqdm
  - pip:
      # - speclite
      - pyhalo==1.3.4
      - hydra-core
      # - colossus
      # - mcfit
      - webbpsf==1.4.0
      - numba==0.58.1
      - lenstronomy==1.12.3
      - slsim==0.1.0
      # - pysiaf
      - pandeia-engine==2024.9.1
      # - sncosmo