name: mejiro-v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - astropy
  - galsim
  - jupyter=1.1.1
  - numpy<2
  - pip
  - pytest  # dev
  - tqdm
  - pip:
    - hydra-core  # temp
    - lenstronomy==1.12.5
    - stpsf==2.0.0
    - pandeia-engine==2024.12
    - pysiaf
    - syotools  # for HWO imaging
    - speclite
    - pyhalo==1.3.5
    - colossus  # needed for pyhalo
    - git+https://github.com/bryce-wedig/slsim.git@mejiro-v2.0.0
    - sncosmo
    - skypy
    # - mcfit
    # - git+https://github.com/bryce-wedig/hwo-tools.git@mejiro-v2.0.0
    - sphinx==7.1.2  # dev
    - sphinx-rtd-theme==1.3.0rc1  # dev
