name: mejiro
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - astropy==5.1.1
  - astroquery
  - jupyter
  - healpy
  - lenstronomy==1.11.0
  - pip
  - scikit-image
  - tqdm
  - pip:
      - pandeia-engine==3.0
      - pyhalo
      - hydra-core
      - colossus
      - mcfit
      - jwst_backgrounds
      - webbpsf==1.1.1
