defaults:
  - _self_
  - machine: uzay
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

survey:
  - runs: 100
  - scas: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]  # 
  - deflector_cut_band: F129
  - deflector_cut_band_max: 25
  - deflector_z_min: 0.01
  - deflector_z_max: 2.
  - source_cut_band: F129
  - source_cut_band_max: 26
  - source_z_min: 0.01
  - source_z_max: 5.
  - min_image_separation: 0.2  # arcseconds
  - max_image_separation: 10.  # arcseconds
  - mag_arc_limit_band: F129
  - mag_arc_limit: 26  # this takes pressure off of SNR criterion, so set as high as possible without missing anything
  - large_lens_mag_max: 14  # for Einstein radius and Sersic radius criterion
  - large_lens_band: F129  # for Einstein radius and Sersic radius criterion
  - snr_subtract_lens: False
  - snr_band: F129
  - snr_threshold: 20
  - snr_mask_multiplier: 1.  # mean + (this factor * stdev) forms mask around arcs
  - zodi_multiplier: 1.5  # multiplied with minimum zodiacal light, used in SNR estimate

pipeline:
  - debugging: True  # debugging mode will print statements to console
  - limit: None  # None
  # scene params
  - num_pix: 96  # 51  # 96
  - side: 10.56  # 5.61  # 10.56
  - final_pixel_side: 90  # 45
  - grid_oversample: 5
  - num_samples: 100000  # 100000
  - max_scene_size: 10.  # 10.01
  # subhalo params
  - log_mlow: 6 
  - log_mhigh: 10
  - subhalo_cone: 10.  # 6.
  - los_normalization: 0.
  - r_tidal: 0.5  # see Section 3.1 of Gilman et al. 2020 https://ui.adsabs.harvard.edu/abs/2020MNRAS.491.6077G/abstract 
  - sigma_sub: 0.055  # see Section 6.3 of Gilman et al. 2020 https://ui.adsabs.harvard.edu/abs/2020MNRAS.491.6077G/abstract 
  # imaging params
  - bands: [ F106, F129, F184 ]  # [F087, F106, F129, F158]
  - rgb_bands: [ F184, F129, F106 ]  # in RGB order
  - exposure_time: 146
  # other
  - suppress_output: True
  - seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)
  - pieces: False

hydra:
  output_subdir: null
  run:
    dir: .