defaults:
  - _self_
  - machine: local
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

generate:
  # True for regression (model will estimate Einstein radius)
  # False for classification (model will classify as large or small Einstein radius)
  is_regression: True
  types: [ 'train', 'val', 'test' ]
  num_images: [ 10000, 1000, 1000 ]
  side: 100

seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)

hydra:
  output_subdir: null
  run:
    dir: .