defaults:
  - _self_
  - machine: hpc
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

#   survey:
    # - deflector_cut_band: F106
    # - deflector_cut_band_max: 24
    # - deflector_z_min: 0.01
    # - deflector_z_max: 2.
    # - source_cut_band: F106
    # - source_cut_band_max: 24
    # - source_z_min: 0.01
    # - source_z_max: 5.

pipeline:
  - num_pix: 96  # 45  # 97
  - side: 10.56  # 4.95  # 10.67
  - final_pixel_side: 90
  - grid_oversample: 5
  - num_samples: 100000  # 100000
  - max_scene_size: 10.  # 10.01
  - subhalo_cone: 10.  # 6.
  - los_normalization: 0.
  - bands: [ F106, F129, F184 ]  # [F087, F106, F129, F158, F184]
  - rgb_bands: [ F184, F129, F106 ]  # in RGB order
  - exposure_time: 146
  - suppress_output: True
  - seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)

hydra:
  output_subdir: null
  run:
    dir: .