defaults:
  - _self_
  - machine: uzay
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)

pipeline:
  - num_pix: 97
  - side: 10.67
  - grid_oversample: 3
  - num_samples: 100000
  - max_scene_size: 10.01
  - subhalo_cone: 11.
  - los_normalization: 0.
  - band: [F106, F129, F184]

hydra:
  output_subdir: null
  run:
    dir: .