defaults:
  - _self_
  - machine: hpc
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

survey:
  - runs: 540 # 54
  - area: 0.5
  - total_population: True
  - scas: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]  # 
  - deflector_cut_band: F129
  - deflector_cut_band_max: 27
  - deflector_z_min: 0.01
  - deflector_z_max: 3.
  - source_cut_band: F129
  - source_cut_band_max: 27
  - source_z_min: 0.01
  - source_z_max: 6.
  - min_image_separation: 0.3  # arcseconds
  - max_image_separation: 10.  # arcseconds
  - mag_arc_limit_band: F129
  - mag_arc_limit: 25  # this takes pressure off of SNR criterion, so set as high as possible without missing anything
  - large_lens_mag_max: 12  # 14  # for Einstein radius and Sersic radius criterion
  - large_lens_band: F129  # for Einstein radius and Sersic radius criterion
  - magnification: 3
  - snr_subtract_lens: False
  - snr_add_subhalos: False
  - snr_exposure_time: 146
  - snr_band: F129
  - snr_threshold: 20
  - snr_side: 10.67
  - snr_input_num_pix: 97
  - snr_output_num_pix: 91
  - snr_oversample: 5
  - snr_supersampling_factor: 3
  - snr_supersampling_compute_mode: adaptive  # regular
  - snr_supersampling_radius: 2.
  - snr_adaptive_pad: 40  # number of pixels to pad radii of annular adaptive grid below and above minimum and maximum image positions
  # - zodi_multiplier: 1.5  # multiplied with minimum zodiacal light

pipeline:
  - nice: 19
  - debugging: False  # debugging mode will print statements to console and save output to a different directory (pipeline_dev)
  - limit: None  # None
  # scene params
  - side: 10.67  # 10.67  # 5.61  # 10.56
  - num_pix: 97  # 97  # 51  # 96
  - final_pixel_side: 91  # 45
  - grid_oversample: 5
  - num_samples: 100000  # 100000
  - max_scene_size: 10.01
  - supersampling_factor: 1
  - supersampling_compute_mode: regular
  - supersampling_radius: 3. # arcseconds
  # subhalo params
  - log_mlow: 6
  - log_mhigh: 10
  - subhalo_cone: 10.  # 6.
  - los_normalization: 0.
  - r_tidal: 0.5  # see Section 3.1 of Gilman et al. 2020 https://ui.adsabs.harvard.edu/abs/2020MNRAS.491.6077G/abstract 
  - sigma_sub: 0.055  # see Section 6.3 of Gilman et al. 2020 https://ui.adsabs.harvard.edu/abs/2020MNRAS.491.6077G/abstract 
  # imaging params
  - bands: [ F087, F106, F129, F158, F184 ]  # [F062, F087, F106, F129, F158, F184]
  - rgb_bands: [ F184, F129, F106 ]  # in RGB order
  - rgb_stretch: 3
  - rgb_q: 3
  - exposure_time: 146  # 146
  # other
  - suppress_output: True
  - seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)
  - pieces: False

hydra:
  output_subdir: null
  run:
    dir: .