defaults:
  - _self_
  - machine: hpc
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)

hydra:
  output_subdir: null
  run:
    dir: .