defaults:
  - _self_
  - machine: hpc
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

survey:
  - deflector_cut_band: hdi
  - deflector_cut_band_max: 24
  - deflector_z_min: 0.01
  - deflector_z_max: 2.
  - source_cut_band: hdi
  - source_cut_band_max: 25
  - source_z_min: 0.01
  - source_z_max: 5.

pipeline:
  - num_pix: 720  # 45  # 97
  - side: 4.95  # 4.95  # 10.67
  - final_pixel_side: 720
  - grid_oversample: 5
  - num_samples: 100000  # 100000
  - max_scene_size: 10.  # 10.01
  - subhalo_cone: 10.  # 6.
  - los_normalization: 0.
  - bands: [ hdi ]
  # - rgb_bands: [ hdi ]  # in RGB order
  - exposure_time: 146
  - suppress_output: True
  - seed: 42  # use with e.g. tf.random.set_seed(config.seed), np.random.seed(config.seed)
  - pieces: False
  - limit:   # None
  - survey_sim_runs: 1000

hydra:
  output_subdir: null
  run:
    dir: .