# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - "mejiro/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "mejiro/**"
      - "tests/**"
  workflow_dispatch:  # allow manual triggering of the workflow

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Check out roman-technical-information repository
      uses: actions/checkout@v4
      with:
        repository: RomanSpaceTelescope/roman-technical-information
        path: roman-technical-information
    - name: Set environment variable
      run: echo "ROMAN_TECHNICAL_INFORMATION_PATH=${{ github.workspace }}/roman-technical-information" >> $GITHUB_ENV
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -s -v --ignore tests/test_hwo_imaging --ignore tests/test_engines/test_galsim_engine_hwo.py --ignore tests/test_instruments/test_hwo.py --ignore tests/test_pipeline/test_mejiro_pipeline.py